websoclet2 api
angel-one/smartapi-python pull request #5
Opened 2023-02-13 14:10 UTC by abhijeet-bote

2023-03-01 08:50 UTC, NakshArora requested changes

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +# import threading
Unused imports can be removed.

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +    NSE_CM = 1
Should we maintain exchange types in Map/Dictionary?

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +                "Authorization": self.auth_token,
headers can be extracted out of this try-catch block

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +            parsed_data = {
Please review the code piece which can be extracted out of try-catch block.

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +            return packets
Can you please explain this? What are we doing here?

2023-03-01 08:50 UTC, NakshArora commented on example/sample.py
> +print('data',data)
Not required. This print statement can be removed.

2023-03-01 08:50 UTC, NakshArora commented on example/sample.py
> +    # orderId=obj.placeOrder(orderparams)
Why this is commented?

2023-03-01 08:50 UTC, NakshArora commented on example/sample.py
> +logout
Same here

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +                for key1, val1 in val.items():
Why are we creating a new dict here? Why can't we use val directly?

2023-03-01 08:50 UTC, NakshArora commented on SmartApi/smartWebSocketV2.py
> +                "exchange_timestamp": self._unpack_data(binary_data, 35, 43, byte_format="q")[0],
We should ideally extract out constants.

2023-03-01 08:51 UTC, NakshArora commented
Can you please provide a short description and test plan for this PR?

2023-07-04 16:41 UTC, sid-agr approved these changes

2024-09-12 04:33 UTC, Ankitkalauni commented
where to find the stock name, token/symbol number?

2025-11-14 04:50 UTC, closed without merging